### PR TITLE
Added Arch to the benchmarks.

### PR DESCRIPTION
**Pull request by genaray**
Added Arch ECS to the benchmarks :)

### CODE REVIEW

**Comment by genaray** [comment]
Would be great if you could take a quick look at it.
Since Arch ECS uses an archetype based approach with dense packing... i skipped the padding stuff. I hope thats okay, atleast i couldnt find any way to simulate such a padding for archetypes ^^ 

Updated results and arch should still be added to the readme.

-- Edit --
I just noticed that theres still an small mistake in arch, i actually modified my source generator to cache queries. However it looks like it does not right now and the old generated sources are still in there. Im gonna fix this.

**Comment by genaray** [comment]
Done now :)

**Comment by Doraku** [comment]
Thanks, I'll make it run properly during the day to update the results :)

> Since Arch ECS uses an archetype based approach with dense packing... i skipped the padding stuff. I hope thats okay, atleast i couldnt find any way to simulate such a padding for archetypes ^^

yeah it make sense, if each archetype has its own component storages, having more entities of a different archetype shouldn't have any impact.

**Comment by genaray** [comment]
> Thanks, I'll make it run properly during the day to update the results :)
> 
> > Since Arch ECS uses an archetype based approach with dense packing... i skipped the padding stuff. I hope thats okay, atleast i couldnt find any way to simulate such a padding for archetypes ^^
> 
> yeah it make sense, if each archetype has its own component storages, having more entities of a different archetype shouldn't have any impact.

Thanks a lot, exciting how it turns out ! And sorry for the code cleanup which i was the reason for, just saw that my IDE settings probably still had the java like code style enabled ^^ Next time i will make sure to use the right one.

**Comment by Doraku** [comment]
no worries there was an issue in the pull request github action anyway, normally you would see it in the ci result https://github.com/Doraku/Ecs.CSharp.Benchmark/actions/runs/3380824045

**Pull request merged**
